function [marrtCorr, amat] = MaritalSorting(solutionSP, param, gridS, gridP)  

    Act = solutionSP.Act;    
    A = solutionSP.A;
    
    A(param.NSall+1:param.NSall+param.NPall,...
        param.NSall+1:param.NSall+param.NPall) =...
        - (param.pcp+param.zeta).*speye(param.NPall,param.NPall);
    A(param.NSall+param.NPall+param.NSall+1:2*(param.NSall+param.NPall),...
        param.NSall+param.NPall+param.NSall+1:2*(param.NSall+param.NPall)) =...
        - param.zeta.*speye(param.NPall,param.NPall);
    
    %Born single unemployed
    fNew = [(A.*Act + (-param.zeta)*spdiags(1-Act,0,2*(param.NSall+param.NPall),2*(param.NSall+param.NPall)))';...
            ones(1,2*(param.NSall+param.NPall))]\...
            [zeros(param.NS,1);-param.zeta*param.a.erg;...
            zeros(param.NPall,1);zeros(param.NSall+param.NPall,1);1];
    
    %Born single
%     SingleDist = [reshape(solutionS.e,param.NS,1); solutionS.h+solutionS.o+solutionS.oc];
%     SingleDist = SingleDist./sum(SingleDist,'all');
%     fNew = [(solutionSP.A.*Act + (-param.zeta)*spdiags(1-Act,0,2*(param.NSall+param.NPall),2*(param.NSall+param.NPall)))';...
%             ones(1,2*(param.NSall+param.NPall))]\...
%             [-param.zeta*SingleDist;...
%             zeros(param.NPall,1);zeros(param.NSall+param.NPall,1);1];
        
      %Born single or married unemployed  
%     fNew = [(solutionSP.A.*Act + (-param.zeta)*spdiags(1-Act,0,2*(param.NSall+param.NPall),2*(param.NSall+param.NPall)))';...
%         ones(1,2*(param.NSall+param.NPall))]\...
%         [zeros(param.NS,1);-param.zeta*0.5*param.a.erg;...
%         zeros(param.NPall-gridP.a1.n*gridP.a2.n,1);...
%         -param.zeta*0.5*reshape(param.a.erg.*param.a.erg',...
%         gridP.a1.n*gridP.a2.n,1);zeros(param.NSall+param.NPall,1);1];
            
    
    fIn = fNew.*Act;    
    
    solutionSP.e = reshape(fIn(1:param.NS), size(solutionSP.JValue));
    solutionSP.h = reshape(fIn(param.NS+1:param.NSall), size(solutionSP.UValue));    
    solutionSP.ee = reshape(fIn(param.NSall+1:param.NSall+param.NP), size(solutionSP.JJValue)); 
    solutionSP.eh = reshape(fIn(param.NSall+param.NP+1:param.NSall+param.NP+param.NP/gridP.r2.n), size(solutionSP.JUValue)); 
    solutionSP.he = reshape(fIn(param.NSall+param.NP+param.NP/gridP.r2.n+1:param.NSall+param.NP+param.NP/gridP.r2.n+param.NP/gridP.r1.n), size(solutionSP.UJValue)); 
    solutionSP.hh = reshape(fIn(param.NSall+param.NP+param.NP/gridP.r2.n+param.NP/gridP.r1.n+1:param.NSall+param.NPall), size(solutionSP.UUValue)); 
    
    solutionSP.ec = reshape(fIn(param.NSall+param.NPall+1:param.NSall+param.NPall+param.NS), size(solutionSP.JcValue));
    solutionSP.hc = reshape(fIn(param.NSall+param.NPall+param.NS+1:param.NSall+param.NPall+param.NSall), size(solutionSP.UcValue));    
    solutionSP.eec = reshape(fIn(param.NSall+param.NPall+param.NSall+1:param.NSall+param.NPall+param.NSall+param.NP), size(solutionSP.JJcValue)); 
    solutionSP.ehc = reshape(fIn(param.NSall+param.NPall+param.NSall+param.NP+1:param.NSall+param.NPall+param.NSall+param.NP+param.NP/gridP.r2.n), size(solutionSP.JUcValue)); 
    solutionSP.hec = reshape(fIn(param.NSall+param.NPall+param.NSall+param.NP+param.NP/gridP.r2.n+1:param.NSall+param.NPall+param.NSall+param.NP+param.NP/gridP.r2.n+param.NP/gridP.r1.n), size(solutionSP.UJcValue)); 
    solutionSP.hhc = reshape(fIn(param.NSall+param.NPall+param.NSall+param.NP+param.NP/gridP.r2.n+param.NP/gridP.r1.n+1:end), size(solutionSP.UUcValue));    
    
    
    fOut = fNew.*(1-Act);
    solutionSP.fOut=fOut;
    solutionSP.out=sum(fOut,'all');
    
    %plot ability heatmap
    den = squeeze(sum(solutionSP.ee, [2,4]))+...
                                          squeeze(sum(solutionSP.eh, 2))+...
                                          squeeze(sum(solutionSP.he, 3))+...                                          
                                          squeeze((solutionSP.hh))+...
                                          squeeze(sum(solutionSP.eec, [2,4]))+...
                                          squeeze(sum(solutionSP.ehc, 2))+...
                                          squeeze(sum(solutionSP.hec, 3))+...                                          
                                          squeeze((solutionSP.hhc));
    fig = heatmap(gridP.a1.a, gridP.a2.a, den./sum(den,1));
    title('Marital sorting in ability');
    xlabel('Ability respondent');
    ylabel('Ability spouse');
    saveas(fig, 'Plots/EndogMarrHeatmap.png');
        

           
    function cov = findCov(g1, g2, ee, eh, he, hh)
        sumdist = (sum(ee,'all')+sum(eh,'all')+sum(he,'all')+sum(hh,'all'));
        cov = ((sum((g1.*g2).*ee,'all')+...
                sum(squeeze(g1(:,:,:,1).*g2(:,:,:,1)).*eh,'all')+...
                sum(squeeze(g1(:,1,:,:).*g2(:,1,:,:)).*he,'all')+...
                sum(squeeze(g1(:,1,:,1).*g2(:,1,:,1)).*hh,'all'))/sumdist)-...
                (((sum((g1).*ee,'all')+...
                 sum(squeeze(g1(:,:,:,1)).*eh,'all')+...
                 sum(squeeze(g1(:,1,:,:)).*he,'all')+...
                 sum(squeeze(g1(:,1,:,1)).*hh,'all'))/sumdist)*...
                ((sum((g2).*ee,'all')+...
                 sum(squeeze(g2(:,:,:,1)).*eh,'all')+...
                 sum(squeeze(g2(:,1,:,:)).*he,'all')+...
                 sum(squeeze(g2(:,1,:,1)).*hh,'all'))/sumdist));
    end

    % no KIDS
    marrCov = findCov(gridP.a1.aa, gridP.a2.aa,...
                      solutionSP.ee, solutionSP.eh, solutionSP.he, solutionSP.hh);
    a1Var = findCov(gridP.a1.aa, gridP.a1.aa,...
                      solutionSP.ee, solutionSP.eh, solutionSP.he, solutionSP.hh);
    a2Var = findCov(gridP.a2.aa, gridP.a2.aa,...
                      solutionSP.ee, solutionSP.eh, solutionSP.he, solutionSP.hh);
    marrCorr = marrCov/sqrt(a1Var*a2Var);

    % with KIDS
    marrcCov = findCov(gridP.a1.aa, gridP.a2.aa,...
                      solutionSP.eec, solutionSP.ehc, solutionSP.hec, solutionSP.hhc);
    a1Var = findCov(gridP.a1.aa, gridP.a1.aa,...
                      solutionSP.eec, solutionSP.ehc, solutionSP.hec, solutionSP.hhc);
    a2Var = findCov(gridP.a2.aa, gridP.a2.aa,...
                      solutionSP.eec, solutionSP.ehc, solutionSP.hec, solutionSP.hhc);
    marrcCorr = marrcCov/sqrt(a1Var*a2Var);
    %total
    w1=(gridP.a1.aa);
    w2=(gridP.a2.aa);
    marrtCov = findCov(w1, w2,...
                      solutionSP.ee+solutionSP.eec, solutionSP.eh+solutionSP.ehc,...
                      solutionSP.he+solutionSP.hec, solutionSP.hh+solutionSP.hhc);
    a1Var = findCov(w1, w1,...
                      solutionSP.ee+solutionSP.eec, solutionSP.eh+solutionSP.ehc,...
                      solutionSP.he+solutionSP.hec, solutionSP.hh+solutionSP.hhc);
    a2Var = findCov(w2, w2,...
                      solutionSP.ee+solutionSP.eec, solutionSP.eh+solutionSP.ehc,...
                      solutionSP.he+solutionSP.hec, solutionSP.hh+solutionSP.hhc);
    marrtCorr = marrtCov/sqrt(a1Var*a2Var);
    disp("marr sorting = "+ num2str((marrtCorr)));
    disp("marr sorting no kid = "+ num2str((marrCorr)));
    disp("marr sorting with kid = "+ num2str((marrcCorr)));
    
    amat = squeeze(sum(solutionSP.ee+solutionSP.eec,[2,4]))+...
            squeeze(sum(solutionSP.eh+solutionSP.ehc,2))+...
            squeeze(sum(solutionSP.he+solutionSP.hec,3))+...
            solutionSP.hh+solutionSP.hhc;
    amat=amat./sum(amat,'all');

    
end        